export const modelUrlMap = {
	truckData: './models/seperate-models/truck.gltf',
	gullwingData: './models/seperate-models/gltfpack/gullwing_gltfpack.glb',
	hrHexData: './models/seperate-models/gltfpack/headacheRackHex_gltfpack.glb',
	hrPostData: './models/seperate-models/gltfpack/headacheRackPost_gltfpack.glb',
	LongLSData: './models/seperate-models/gltfpack/longLowSides_gltfpack.glb',
	shortLSData: './models/seperate-models/gltfpack/shortLowSides_gltfpack.glb',
	longFHData: './models/seperate-models/gltfpack/longFlatHatch_gltfpack.glb',
	shortFHdata: './models/seperate-models/gltfpack/shortFlatHatch_gltfpack.glb',
	longDomedData: './models/seperate-models/gltfpack/longDomedHatch_gltfpack.glb',
	shortDomedData: './models/seperate-models/gltfpack/shortDomedHatch_gltfpack.glb',
	shortGladFHData: './models/seperate-models/gltfpack/shortGladiatorFlatHatch_gltfpack.glb',
	longGladFHData: './models/seperate-models/gltfpack/longGladiatorFlatHatch_gltfpack.glb',
	shortGladDHData: './models/seperate-models/gltfpack/shortGladiatorDomedHatch_gltfpack.glb',
	longGladDHData: './models/seperate-models/gltfpack/longGladiatorDomedHatch_gltfpack.glb',
	PupExtrasData: './models/seperate-models/gltfpack/pup_extras_gltfpack.glb',
	TSBaseData: './models/seperate-models/truckslide-base.gltf',
	TSData1200: './models/seperate-models/truckslide-xt1200.gltf',
	TSData2000: './models/seperate-models/truckslide-xt2000.gltf'
};
